### PR TITLE
added link for download button

### PR DESCRIPTION
**Pull request by puterakahfi**
added link for download button

### CODE REVIEW

**Comment by ad3n** [comment]
This branch has conflicts that must be resolved

**Comment by ad3n** [comment]
@puterakahfi : ga bisa di merge om...

**Comment by ucay** [comment]
itu sudah jadi link, si om @puterakahfi  belum pull ya, hehe

**Comment by puterakahfi** [comment]
oh iya dink, saya lupa fetch upstream, tadi ketika di merge ke upstream/master katanya sudah up to date sama branch atasnya.

**Pull request closed without merging**
